# Generated by Django 4.2.6 on 2023-10-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('adhar_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('anual_income', models.BigIntegerField()),
                ('credit_score', models.IntegerField()),
            ],
        ),
    ]
