# Generated by Django 4.2.6 on 2023-10-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_credit_score_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adhar_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
