# Generated by Django 4.2.6 on 2023-10-05 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_adhar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('adhar_id', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
