# Generated by Django 4.2.6 on 2023-10-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transaction_alter_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transactions',
        ),
    ]
