# Generated by Django 4.2.6 on 2023-10-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_transactions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='adhar_id',
            field=models.CharField(max_length=50),
        ),
    ]
