# Generated by Django 4.2.6 on 2023-10-06 03:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_transactions_adhar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=30)),
                ('loan_amount', models.IntegerField()),
                ('intrest_rate', models.IntegerField()),
                ('disbursement_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
