# Generated by Django 4.2.6 on 2023-10-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='term_period',
            field=models.IntegerField(default=0),
        ),
    ]
