# Generated by Django 4.2.6 on 2023-10-06 04:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_loan_term_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('emi_date', models.DateField()),
                ('emi_amount', models.IntegerField()),
                ('paid_amount', models.IntegerField(default=0)),
                ('isPaid', models.BooleanField(default=False)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loan')),
            ],
        ),
    ]
